# -*- coding: utf-8 -*-
# Copyright (c) 2021, Tarlan Ismayilsoy.  All Rights Reserved.
# Copyright (c) 2017, Tufan Kaynak, Framras.  All Rights Reserved.
# Copyright (c) 2003, Taro Ogawa.  All Rights Reserved.
# Copyright (c) 2013, Savoir-faire Linux inc.  All Rights Reserved.

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA

from unittest import TestCase

from num2words import num2words


class Num2WordsAZTest(TestCase):
    def test_az(self):
        testlang = "az"
        testcases = [
            {"test": 0, "to": "currency", "expected": u"pulsuz"},
            {"test": 1.1, "to": "currency", "expected": u"bir manat on qəpik"},
            {"test": 2000, "to": "currency", "expected": u"iki min manat"},
            {"test": 110000, "to": "currency", "expected": u"yüz on min manat"},
            {"test": 1002000, "to": "currency",
             "expected": u"bir milyon iki min manat"},
            {"test": 1002001, "to": "currency",
             "expected": u"bir milyon iki min bir manat"},
            {"test": 1100000, "to": "currency",
             "expected": u"bir milyon yüz min manat"},
            {"test": 0, "to": "ordinal", "expected": u"sıfırıncı"},
            {"test": 1, "to": "ordinal", "expected": u"birinci"},
            {"test": 2, "to": "ordinal", "expected": u"ikinci"},
            {"test": 9, "to": "ordinal", "expected": u"doqquzuncu"},
            {"test": 10, "to": "ordinal", "expected": u"onuncu"},
            {"test": 11, "to": "ordinal", "expected": u"on birinci"},
            {"test": 44, "to": "ordinal", "expected": u"qırx dördüncü"},
            {"test": 100, "to": "ordinal", "expected": u"yüzüncü"},
            {"test": 101, "to": "ordinal", "expected": u"yüz birinci"},
            {"test": 103, "to": "ordinal", "expected": u"yüz üçüncü"},
            {"test": 110, "to": "ordinal", "expected": u"yüz onuncu"},
            {"test": 111, "to": "ordinal", "expected": u"yüz on birinci"},
            {"test": 1000, "to": "ordinal", "expected": u"mininci"},
            {"test": 1001, "to": "ordinal", "expected": u"min birinci"},
            {"test": 1010, "to": "ordinal", "expected": u"min onuncu"},
            {"test": 1011, "to": "ordinal", "expected": u"min on birinci"},
            {"test": 1100, "to": "ordinal", "expected": u"min yüzüncü"},
            {"test": 1110, "to": "ordinal", "expected": u"min yüz onuncu"},
            {"test": 2341, "to": "ordinal",
             "expected": u"iki min üç yüz qırx birinci"},
            {"test": 10000, "to": "ordinal", "expected": u"on mininci"},
            {"test": 10010, "to": "ordinal", "expected": u"on min onuncu"},
            {"test": 10100, "to": "ordinal", "expected": u"on min yüzüncü"},
            {"test": 10110, "to": "ordinal", "expected": u"on min yüz onuncu"},
            {"test": 11000, "to": "ordinal", "expected": u"on bir mininci"},
            {"test": 35000, "to": "ordinal", "expected": u"otuz beş mininci"},
            {"test": 116331, "to": "ordinal",
             "expected": u"yüz on altı min üç yüz otuz birinci"},
            {"test": 116330, "to": "ordinal",
             "expected": u"yüz on altı min üç yüz otuzuncu"},
            {"test": 100000, "to": "ordinal", "expected": u"yüz mininci"},
            {"test": 501000, "to": "ordinal",
             "expected": u"beş yüz bir mininci"},
            {"test": 1000111, "to": "ordinal",
             "expected": u"bir milyon yüz on birinci"},
            {"test": 111000111, "to": "ordinal",
             "expected": u"yüz on bir milyon yüz on birinci"},
            {"test": 111001111, "to": "ordinal",
             "expected": u"yüz on bir milyon min yüz on birinci"},
            {"test": 111111111, "to": "ordinal",
             "expected": u"yüz on bir milyon yüz on bir min yüz on birinci"},
            {"test": 100001000, "to": "ordinal",
             "expected": u"yüz milyon mininci"},
            {"test": 100001001, "to": "ordinal",
             "expected": u"yüz milyon min birinci"},
            {"test": 100010000, "to": "ordinal",
             "expected": u"yüz milyon on mininci"},
            {"test": 100010001, "to": "ordinal",
             "expected": u"yüz milyon on min birinci"},
            {"test": 100011000, "to": "ordinal",
             "expected": u"yüz milyon on bir mininci"},
            {"test": 100011001, "to": "ordinal",
             "expected": u"yüz milyon on bir min birinci"},
            {"test": 101011001, "to": "ordinal",
             "expected": u"yüz bir milyon on bir min birinci"},
            {"test": 101011010, "to": "ordinal",
             "expected": u"yüz bir milyon on bir min onuncu"},
            {"test": 1101011010, "to": "ordinal",
             "expected": u"bir milyard yüz bir milyon on bir min onuncu"},
            {"test": 101101011010, "to": "ordinal",
             "expected": u"yüz bir milyard yüz bir milyon on bir min onuncu"},
            {"test": 1000000000001, "to": "ordinal",
             "expected": u"bir trilyon birinci"},
            {"test": 1.2, "to": "ordinal", "expected": u""},
            {"test": 1.3, "to": "ordinal", "expected": u""},
            {"test": 3000, "to": "ordinal", "expected": u"üç mininci"},
            {"test": 120000, "to": "ordinal", "expected": u"yüz iyirmi mininci"},
            {"test": 1002002, "to": "ordinal",
             "expected": u"bir milyon iki min ikinci"},
            {"test": 1003000, "to": "ordinal",
             "expected": u"bir milyon üç mininci"},
            {"test": 1200000, "to": "ordinal",
             "expected": u"bir milyon iki yüz mininci"},
            {"test": 0, "to": "cardinal", "expected": u"sıfır"},
            {"test": 1, "to": "cardinal", "expected": u"bir"},
            {"test": 2, "to": "cardinal", "expected": u"iki"},
            {"test": 9, "to": "cardinal", "expected": u"doqquz"},
            {"test": 10, "to": "cardinal", "expected": u"on"},
            {"test": 11, "to": "cardinal", "expected": u"on bir"},
            {"test": 44, "to": "cardinal", "expected": u"qırx dörd"},
            {"test": 100, "to": "cardinal", "expected": u"yüz"},
            {"test": 101, "to": "cardinal", "expected": u"yüz bir"},
            {"test": 103, "to": "cardinal", "expected": u"yüz üç"},
            {"test": 110, "to": "cardinal", "expected": u"yüz on"},
            {"test": 111, "to": "cardinal", "expected": u"yüz on bir"},
            {"test": 1000, "to": "cardinal", "expected": u"min"},
            {"test": 1001, "to": "cardinal", "expected": u"min bir"},
            {"test": 1010, "to": "cardinal", "expected": u"min on"},
            {"test": 1011, "to": "cardinal", "expected": u"min on bir"},
            {"test": 1100, "to": "cardinal", "expected": u"min yüz"},
            {"test": 1110, "to": "cardinal", "expected": u"min yüz on"},
            {"test": 2341, "to": "cardinal",
             "expected": u"iki min üç yüz qırx bir"},
            {"test": 10000, "to": "cardinal", "expected": u"on min"},
            {"test": 10010, "to": "cardinal", "expected": u"on min on"},
            {"test": 10100, "to": "cardinal", "expected": u"on min yüz"},
            {"test": 10110, "to": "cardinal", "expected": u"on min yüz on"},
            {"test": 11000, "to": "cardinal", "expected": u"on bir min"},
            {"test": 35000, "to": "cardinal", "expected": u"otuz beş min"},
            {"test": 116331, "to": "cardinal",
             "expected": u"yüz on altı min üç yüz otuz bir"},
            {"test": 116330, "to": "cardinal",
             "expected": u"yüz on altı min üç yüz otuz"},
            {"test": 500000, "to": "cardinal", "expected": u"beş yüz min"},
            {"test": 501000, "to": "cardinal", "expected": u"beş yüz bir min"},
            {"test": 1000111, "to": "cardinal",
             "expected": u"bir milyon yüz on bir"},
            {"test": 111000111, "to": "cardinal",
             "expected": u"yüz on bir milyon yüz on bir"},
            {"test": 111001111, "to": "cardinal",
             "expected": u"yüz on bir milyon min yüz on bir"},
            {"test": 111111111, "to": "cardinal",
             "expected": u"yüz on bir milyon yüz on bir min yüz on bir"},
            {"test": 100001000, "to": "cardinal",
             "expected": u"yüz milyon min"},
            {"test": 100001001, "to": "cardinal",
             "expected": u"yüz milyon min bir"},
            {"test": 100010000, "to": "cardinal",
             "expected": u"yüz milyon on min"},
            {"test": 100010001, "to": "cardinal",
             "expected": u"yüz milyon on min bir"},
            {"test": 100011000, "to": "cardinal",
             "expected": u"yüz milyon on bir min"},
            {"test": 100011001, "to": "cardinal",
             "expected": u"yüz milyon on bir min bir"},
            {"test": 101011001, "to": "cardinal",
             "expected": u"yüz bir milyon on bir min bir"},
            {"test": 101011010, "to": "cardinal",
             "expected": u"yüz bir milyon on bir min on"},
            {"test": 1101011010, "to": "cardinal",
             "expected": u"bir milyard yüz bir milyon on bir min on"},
            {"test": 101101011010, "to": "cardinal",
             "expected": u"yüz bir milyard yüz bir milyon on bir min on"},
            {"test": 1000000000001, "to": "cardinal",
             "expected": u"bir trilyon bir"},
            {"test": 0.01, "to": "cardinal", "expected": u"sıfır vergül bir"},
            {"test": 0.21, "to": "cardinal",
             "expected": u"sıfır vergül iyirmi bir"},
            {"test": 0.1, "to": "cardinal", "expected": u"sıfır vergül on"},
            {"test": 1.01, "to": "cardinal", "expected": u"bir vergül bir"},
            {"test": 1.1, "to": "cardinal", "expected": u"bir vergül on"},
            {"test": 1.21, "to": "cardinal",
             "expected": u"bir vergül iyirmi bir"},
            {"test": 101101011010.02, "to": "cardinal",
             "expected": u"yüz bir milyard yüz bir milyon on bir min on vergül iki"},
            {"test": 101101011010.2, "to": "cardinal",
             "expected": u"yüz bir milyard yüz bir milyon on bir min on vergül iyirmi"}
        ]

        for casedata in testcases:
            self.assertEqual(
                num2words(casedata["test"],
                          lang=testlang,
                          to=casedata["to"]),
                casedata["expected"])
