# -*- coding: utf-8 -*-
# Copyright (c) 2017, Tufan Kaynak, Framras.  All Rights Reserved.
# Copyright (c) 2003, Taro Ogawa.  All Rights Reserved.
# Copyright (c) 2013, Savoir-faire Linux inc.  All Rights Reserved.

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA

from unittest import TestCase

from num2words import num2words


class Num2WordsTRTest(TestCase):
    def test_tr(self):
        # ref https://github.com/savoirfairelinux/num2words/issues/8
        testlang = "tr"
        testcases = [
            {"test": 0, "to": "currency", "expected": u"bedelsiz"},
            {"test": 1.1, "to": "currency", "expected": u"bir lira on kuruş"},
            {"test": 2000, "to": "currency", "expected": u"iki bin lira"},
            {"test": 110000, "to": "currency", "expected": u"yüz on bin lira"},
            {"test": 1002000, "to": "currency",
             "expected": u"bir milyon iki bin lira"},
            {"test": 1002001, "to": "currency",
             "expected": u"bir milyon iki bin bir lira"},
            {"test": 1100000, "to": "currency",
             "expected": u"bir milyon yüz bin lira"},
            {"test": 1, "to": "ordinal", "expected": u"birinci"},
            {"test": 2, "to": "ordinal", "expected": u"ikinci"},
            {"test": 9, "to": "ordinal", "expected": u"dokuzuncu"},
            {"test": 10, "to": "ordinal", "expected": u"onuncu"},
            {"test": 11, "to": "ordinal", "expected": u"on birinci"},
            {"test": 44, "to": "ordinal", "expected": u"kırk dördüncü"},
            {"test": 100, "to": "ordinal", "expected": u"yüzüncü"},
            {"test": 101, "to": "ordinal", "expected": u"yüz birinci"},
            {"test": 103, "to": "ordinal", "expected": u"yüz üçüncü"},
            {"test": 110, "to": "ordinal", "expected": u"yüz onuncu"},
            {"test": 111, "to": "ordinal", "expected": u"yüz on birinci"},
            {"test": 1000, "to": "ordinal", "expected": u"bininci"},
            {"test": 1001, "to": "ordinal", "expected": u"bin birinci"},
            {"test": 1010, "to": "ordinal", "expected": u"bin onuncu"},
            {"test": 1011, "to": "ordinal", "expected": u"bin on birinci"},
            {"test": 1100, "to": "ordinal", "expected": u"bin yüzüncü"},
            {"test": 1110, "to": "ordinal", "expected": u"bin yüz onuncu"},
            {"test": 2341, "to": "ordinal",
             "expected": u"ikibinüçyüzkırkbirinci"},
            {"test": 10000, "to": "ordinal", "expected": u"on bininci"},
            {"test": 10010, "to": "ordinal", "expected": u"on bin onuncu"},
            {"test": 10100, "to": "ordinal", "expected": u"on bin yüzüncü"},
            {"test": 10110, "to": "ordinal", "expected": u"on bin yüz onuncu"},
            {"test": 11000, "to": "ordinal", "expected": u"on bir bininci"},
            {"test": 35000, "to": "ordinal", "expected": u"otuz beş bininci"},
            {"test": 116331, "to": "ordinal",
             "expected": u"yüz on altı bin üç yüz otuz birinci"},
            {"test": 116330, "to": "ordinal",
             "expected": u"yüz on altı bin üç yüz otuzuncu"},
            {"test": 100000, "to": "ordinal", "expected": u"yüz bininci"},
            {"test": 501000, "to": "ordinal",
             "expected": u"beş yüz bir bininci"},
            {"test": 1000111, "to": "ordinal",
             "expected": u"bir milyon yüz on birinci"},
            {"test": 111000111, "to": "ordinal",
             "expected": u"yüz on bir milyon yüz on birinci"},
            {"test": 111001111, "to": "ordinal",
             "expected": u"yüz on bir milyon bin yüz on birinci"},
            {"test": 111111111, "to": "ordinal",
             "expected": u"yüz on bir milyon yüz on bir bin yüz on birinci"},
            {"test": 100001000, "to": "ordinal",
             "expected": u"yüz milyon bininci"},
            {"test": 100001001, "to": "ordinal",
             "expected": u"yüz milyon bin birinci"},
            {"test": 100010000, "to": "ordinal",
             "expected": u"yüz milyon on bininci"},
            {"test": 100010001, "to": "ordinal",
             "expected": u"yüz milyon on bin birinci"},
            {"test": 100011000, "to": "ordinal",
             "expected": u"yüz milyon on bir bininci"},
            {"test": 100011001, "to": "ordinal",
             "expected": u"yüz milyon on bir bin birinci"},
            {"test": 101011001, "to": "ordinal",
             "expected": u"yüz bir milyon on bir bin birinci"},
            {"test": 101011010, "to": "ordinal",
             "expected": u"yüz bir milyon on bir bin onuncu"},
            {"test": 1101011010, "to": "ordinal",
             "expected": u"bir milyar yüz bir milyon on bir bin onuncu"},
            {"test": 101101011010, "to": "ordinal",
             "expected": u"yüz bir milyar yüz bir milyon on bir bin onuncu"},
            {"test": 1000000000001, "to": "ordinal",
             "expected": u"bir trilyon birinci"},
            {"test": 1.2, "to": "ordinal", "expected": u""},
            {"test": 1.3, "to": "ordinal", "expected": u""},
            {"test": 3000, "to": "ordinal", "expected": u"üç bininci"},
            {"test": 120000, "to": "ordinal", "expected": u"yüz yirmi bininci"},
            {"test": 1002002, "to": "ordinal",
             "expected": u"bir milyon iki bin ikinci"},
            {"test": 1003000, "to": "ordinal",
             "expected": u"bir milyon üç bininci"},
            {"test": 1200000, "to": "ordinal",
             "expected": u"bir milyon iki yüz bininci"},
            {"test": 1, "to": "cardinal", "expected": u"bir"},
            {"test": 2, "to": "cardinal", "expected": u"iki"},
            {"test": 9, "to": "cardinal", "expected": u"dokuz"},
            {"test": 10, "to": "cardinal", "expected": u"on"},
            {"test": 11, "to": "cardinal", "expected": u"onbir"},
            {"test": 44, "to": "cardinal", "expected": u"kırk dört"},
            {"test": 100, "to": "cardinal", "expected": u"yüz"},
            {"test": 101, "to": "cardinal", "expected": u"yüz bir"},
            {"test": 103, "to": "cardinal", "expected": u"yüz üç"},
            {"test": 110, "to": "cardinal", "expected": u"yüz on"},
            {"test": 111, "to": "cardinal", "expected": u"yüz on bir"},
            {"test": 1000, "to": "cardinal", "expected": u"bin"},
            {"test": 1001, "to": "cardinal", "expected": u"bin bir"},
            {"test": 1010, "to": "cardinal", "expected": u"bin on"},
            {"test": 1011, "to": "cardinal", "expected": u"bin on bir"},
            {"test": 1100, "to": "cardinal", "expected": u"bin yüz"},
            {"test": 1110, "to": "cardinal", "expected": u"bin yüz on"},
            {"test": 2341, "to": "cardinal",
             "expected": u"iki bin üç yüz kırk bir"},
            {"test": 10000, "to": "cardinal", "expected": u"on bin"},
            {"test": 10010, "to": "cardinal", "expected": u"on bin on"},
            {"test": 10100, "to": "cardinal", "expected": u"on bin yüz"},
            {"test": 10110, "to": "cardinal", "expected": u"on bin yüz on"},
            {"test": 11000, "to": "cardinal", "expected": u"on bir bin"},
            {"test": 35000, "to": "cardinal", "expected": u"otuz beş bin"},
            {"test": 116331, "to": "cardinal",
             "expected": u"yüz on altı bin üç yüz otuz bir"},
            {"test": 116330, "to": "cardinal",
             "expected": u"yüz on altı bin üç yüz otuz"},
            {"test": 500000, "to": "cardinal", "expected": u"beş yüz bin"},
            {"test": 501000, "to": "cardinal", "expected": u"beş yüz bir bin"},
            {"test": 1000111, "to": "cardinal",
             "expected": u"bir milyon yüz on bir"},
            {"test": 111000111, "to": "cardinal",
             "expected": u"yüz on bir milyon yüz on bir"},
            {"test": 111001111, "to": "cardinal",
             "expected": u"yüz on bir milyon bin yüz on bir"},
            {"test": 111111111, "to": "cardinal",
             "expected": u"yüz on bir milyon yüz on bir bin yüz on bir"},
            {"test": 100001000, "to": "cardinal",
             "expected": u"yüz milyon bin"},
            {"test": 100001001, "to": "cardinal",
             "expected": u"yüz milyon bin bir"},
            {"test": 100010000, "to": "cardinal",
             "expected": u"yüz milyon on bin"},
            {"test": 100010001, "to": "cardinal",
             "expected": u"yüz milyon on bin bir"},
            {"test": 100011000, "to": "cardinal",
             "expected": u"yüz milyon on bir bin"},
            {"test": 100011001, "to": "cardinal",
             "expected": u"yüz milyon on bir bin bir"},
            {"test": 101011001, "to": "cardinal",
             "expected": u"yüz bir milyon on bir bin bir"},
            {"test": 101011010, "to": "cardinal",
             "expected": u"yüz bir milyon on bir bin on"},
            {"test": 1101011010, "to": "cardinal",
             "expected": u"bir milyar yüz bir milyon on bir bin on"},
            {"test": 101101011010, "to": "cardinal",
             "expected": u"yüz bir milyar yüz bir milyon on bir bin on"},
            {"test": 1000000000001, "to": "cardinal",
             "expected": u"bir trilyon bir"},
            {"test": 0.01, "to": "cardinal", "expected": u"sıfır nokta bir"},
            {"test": 0.21, "to": "cardinal",
             "expected": u"sıfır nokta yirmi bir"},
            {"test": 0.1, "to": "cardinal", "expected": u"sıfır nokta on"},
            {"test": 1.01, "to": "cardinal", "expected": u"bir nokta bir"},
            {"test": 1.1, "to": "cardinal", "expected": u"bir nokta on"},
            {"test": 1.21, "to": "cardinal",
             "expected": u"bir nokta yirmi bir"},
            {"test": 101101011010.02, "to": "cardinal",
             "expected": u"yüz bir milyar yüz bir milyon on bir bin on nokta iki"},
            {"test": 101101011010.2, "to": "cardinal",
             "expected": u"yüz bir milyar yüz bir milyon on bir bin on nokta yirmi"}
        ]

        for casedata in testcases:
            self.assertEqual(
                num2words(casedata["test"],
                          lang=testlang,
                          to=casedata["to"]),
                casedata["expected"])
