# -*- coding: utf-8 -*-
# Copyright (c) 2017, Tufan Kaynak, Framras.  All Rights Reserved.
# Copyright (c) 2003, Taro Ogawa.  All Rights Reserved.
# Copyright (c) 2013, Savoir-faire Linux inc.  All Rights Reserved.

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA

from unittest import TestCase

from num2words import num2words


class Num2WordsBATest(TestCase):
    def test_ba(self):
        testlang = "ba"
        testcases = [
            {"test": 0, "to": "currency", "expected": u"бушлай"},
            {"test": 1.1, "to": "currency", "expected": u"бер һум ун тин"},
            {"test": 2000, "to": "currency", "expected": u"ике мең һум"},
            {"test": 110000, "to": "currency", "expected": u"йөҙ ун мең һум"},
            {"test": 1002000, "to": "currency",
             "expected": u"бер миллион ике мең һум"},
            {"test": 1002001, "to": "currency",
             "expected": u"бер миллион ике мең бер һум"},
            {"test": 1100000, "to": "currency",
             "expected": u"бер миллион йөҙ мең һум"},
            {"test": 0, "to": "ordinal", "expected": u"нуленсе"},
            {"test": 1, "to": "ordinal", "expected": u"беренсе"},
            {"test": 2, "to": "ordinal", "expected": u"икенсе"},
            {"test": 9, "to": "ordinal", "expected": u"туғыҙынсы"},
            {"test": 10, "to": "ordinal", "expected": u"унынсы"},
            {"test": 11, "to": "ordinal", "expected": u"ун беренсе"},
            {"test": 44, "to": "ordinal", "expected": u"ҡырҡ дүртенсе"},
            {"test": 100, "to": "ordinal", "expected": u"йөҙөнсө"},
            {"test": 101, "to": "ordinal", "expected": u"йөҙ беренсе"},
            {"test": 103, "to": "ordinal", "expected": u"йөҙ өсөнсө"},
            {"test": 110, "to": "ordinal", "expected": u"йөҙ унынсы"},
            {"test": 111, "to": "ordinal", "expected": u"йөҙ ун беренсе"},
            {"test": 1000, "to": "ordinal", "expected": u"меңенсе"},
            {"test": 1001, "to": "ordinal", "expected": u"мең беренсе"},
            {"test": 1010, "to": "ordinal", "expected": u"мең унынсы"},
            {"test": 1011, "to": "ordinal", "expected": u"мең ун беренсе"},
            {"test": 1100, "to": "ordinal", "expected": u"мең йөҙөнсө"},
            {"test": 1110, "to": "ordinal", "expected": u"мең йөҙ унынсы"},
            {"test": 2341, "to": "ordinal", "expected": u"ике мең өс йөҙ ҡырҡ беренсе"},
            {"test": 10000, "to": "ordinal", "expected": u"ун меңенсе"},
            {"test": 10010, "to": "ordinal", "expected": u"ун мең унынсы"},
            {"test": 10100, "to": "ordinal", "expected": u"ун мең йөҙөнсө"},
            {"test": 10110, "to": "ordinal", "expected": u"ун мең йөҙ унынсы"},
            {"test": 11000, "to": "ordinal", "expected": u"ун бер меңенсе"},
            {"test": 35000, "to": "ordinal", "expected": u"утыҙ биш меңенсе"},
            {"test": 116331, "to": "ordinal",
             "expected": u"йөҙ ун алты мең өс йөҙ утыҙ беренсе"},
            {"test": 116330, "to": "ordinal",
             "expected": u"йөҙ ун алты мең өс йөҙ утыҙынсы"},
            {"test": 100000, "to": "ordinal", "expected": u"йөҙ меңенсе"},
            {"test": 501000, "to": "ordinal",
             "expected": u"биш йөҙ бер меңенсе"},
            {"test": 1000111, "to": "ordinal",
             "expected": u"бер миллион йөҙ ун беренсе"},
            {"test": 111000111, "to": "ordinal",
             "expected": u"йөҙ ун бер миллион йөҙ ун беренсе"},
            {"test": 111001111, "to": "ordinal",
             "expected": u"йөҙ ун бер миллион мең йөҙ ун беренсе"},
            {"test": 111111111, "to": "ordinal",
             "expected": u"йөҙ ун бер миллион йөҙ ун бер мең йөҙ ун беренсе"},
            {"test": 100001000, "to": "ordinal",
             "expected": u"йөҙ миллион меңенсе"},
            {"test": 100001001, "to": "ordinal",
             "expected": u"йөҙ миллион мең беренсе"},
            {"test": 100010000, "to": "ordinal",
             "expected": u"йөҙ миллион ун меңенсе"},
            {"test": 100010001, "to": "ordinal",
             "expected": u"йөҙ миллион ун мең беренсе"},
            {"test": 100011000, "to": "ordinal",
             "expected": u"йөҙ миллион ун бер меңенсе"},
            {"test": 100011001, "to": "ordinal",
             "expected": u"йөҙ миллион ун бер мең беренсе"},
            {"test": 101011001, "to": "ordinal",
             "expected": u"йөҙ бер миллион ун бер мең беренсе"},
            {"test": 101011010, "to": "ordinal",
             "expected": u"йөҙ бер миллион ун бер мең унынсы"},
            {"test": 1101011010, "to": "ordinal",
             "expected": u"бер миллиард йөҙ бер миллион ун бер мең унынсы"},
            {"test": 101101011010, "to": "ordinal",
             "expected": u"йөҙ бер миллиард йөҙ бер миллион ун бер мең унынсы"},
            {"test": 1000000000001, "to": "ordinal",
             "expected": u"бер триллион беренсе"},
            {"test": 1.2, "to": "ordinal", "expected": u""},
            {"test": 1.3, "to": "ordinal", "expected": u""},
            {"test": 3000, "to": "ordinal", "expected": u"өс меңенсе"},
            {"test": 120000, "to": "ordinal", "expected": u"йөҙ егерме меңенсе"},
            {"test": 1002002, "to": "ordinal",
             "expected": u"бер миллион ике мең икенсе"},
            {"test": 1003000, "to": "ordinal",
             "expected": u"бер миллион өс меңенсе"},
            {"test": 1200000, "to": "ordinal",
             "expected": u"бер миллион ике йөҙ меңенсе"},
            {"test": 0, "to": "cardinal", "expected": u"ноль"},
            {"test": 1, "to": "cardinal", "expected": u"бер"},
            {"test": 2, "to": "cardinal", "expected": u"ике"},
            {"test": 9, "to": "cardinal", "expected": u"туғыҙ"},
            {"test": 10, "to": "cardinal", "expected": u"ун"},
            {"test": 11, "to": "cardinal", "expected": u"ун бер"},
            {"test": 44, "to": "cardinal", "expected": u"ҡырҡ дүрт"},
            {"test": 100, "to": "cardinal", "expected": u"йөҙ"},
            {"test": 101, "to": "cardinal", "expected": u"йөҙ бер"},
            {"test": 103, "to": "cardinal", "expected": u"йөҙ өс"},
            {"test": 110, "to": "cardinal", "expected": u"йөҙ ун"},
            {"test": 111, "to": "cardinal", "expected": u"йөҙ ун бер"},
            {"test": 1000, "to": "cardinal", "expected": u"мең"},
            {"test": 1001, "to": "cardinal", "expected": u"мең бер"},
            {"test": 1010, "to": "cardinal", "expected": u"мең ун"},
            {"test": 1011, "to": "cardinal", "expected": u"мең ун бер"},
            {"test": 1100, "to": "cardinal", "expected": u"мең йөҙ"},
            {"test": 1110, "to": "cardinal", "expected": u"мең йөҙ ун"},
            {"test": 2341, "to": "cardinal",
             "expected": u"ике мең өс йөҙ ҡырҡ бер"},
            {"test": 10000, "to": "cardinal", "expected": u"ун мең"},
            {"test": 10010, "to": "cardinal", "expected": u"ун мең ун"},
            {"test": 10100, "to": "cardinal", "expected": u"ун мең йөҙ"},
            {"test": 10110, "to": "cardinal", "expected": u"ун мең йөҙ ун"},
            {"test": 11000, "to": "cardinal", "expected": u"ун бер мең"},
            {"test": 35000, "to": "cardinal", "expected": u"утыҙ биш мең"},
            {"test": 116331, "to": "cardinal",
             "expected": u"йөҙ ун алты мең өс йөҙ утыҙ бер"},
            {"test": 116330, "to": "cardinal",
             "expected": u"йөҙ ун алты мең өс йөҙ утыҙ"},
            {"test": 500000, "to": "cardinal", "expected": u"биш йөҙ мең"},
            {"test": 501000, "to": "cardinal", "expected": u"биш йөҙ бер мең"},
            {"test": 1000111, "to": "cardinal",
             "expected": u"бер миллион йөҙ ун бер"},
            {"test": 111000111, "to": "cardinal",
             "expected": u"йөҙ ун бер миллион йөҙ ун бер"},
            {"test": 111001111, "to": "cardinal",
             "expected": u"йөҙ ун бер миллион мең йөҙ ун бер"},
            {"test": 111111111, "to": "cardinal",
             "expected": u"йөҙ ун бер миллион йөҙ ун бер мең йөҙ ун бер"},
            {"test": 100001000, "to": "cardinal",
             "expected": u"йөҙ миллион мең"},
            {"test": 100001001, "to": "cardinal",
             "expected": u"йөҙ миллион мең бер"},
            {"test": 100010000, "to": "cardinal",
             "expected": u"йөҙ миллион ун мең"},
            {"test": 100010001, "to": "cardinal",
             "expected": u"йөҙ миллион ун мең бер"},
            {"test": 100011000, "to": "cardinal",
             "expected": u"йөҙ миллион ун бер мең"},
            {"test": 100011001, "to": "cardinal",
             "expected": u"йөҙ миллион ун бер мең бер"},
            {"test": 101011001, "to": "cardinal",
             "expected": u"йөҙ бер миллион ун бер мең бер"},
            {"test": 101011010, "to": "cardinal",
             "expected": u"йөҙ бер миллион ун бер мең ун"},
            {"test": 1101011010, "to": "cardinal",
             "expected": u"бер миллиард йөҙ бер миллион ун бер мең ун"},
            {"test": 101101011010, "to": "cardinal",
             "expected": u"йөҙ бер миллиард йөҙ бер миллион ун бер мең ун"},
            {"test": 1000000000001, "to": "cardinal",
             "expected": u"бер триллион бер"},
            {"test": 0.01, "to": "cardinal", "expected": u"йөҙҙән бер"},
            {"test": 0.21, "to": "cardinal",
             "expected": u"йөҙҙән егерме бер"},
            {"test": 0.1, "to": "cardinal", "expected": u"ундан бер"},
            {"test": 1.01, "to": "cardinal", "expected": u"бер бөтөн йөҙҙән бер"},
            {"test": 1.1, "to": "cardinal", "expected": u"бер бөтөн ундан бер"},
            {"test": 1.21, "to": "cardinal",
             "expected": u"бер бөтөн йөҙҙән егерме бер"},
            {"test": 101101011010.02, "to": "cardinal",
             "expected": u"йөҙ бер миллиард йөҙ бер миллион ун бер мең ун бөтөн йөҙҙән ике"},
            {"test": 101101011010.2, "to": "cardinal",
             "expected": u"йөҙ бер миллиард йөҙ бер миллион ун бер мең ун бөтөн ундан ике"}
        ]

        for casedata in testcases:
            self.assertEqual(
                num2words(casedata["test"],
                          lang=testlang,
                          to=casedata["to"]),
                casedata["expected"])
